version: '2'

networks:
  app-tier:
    driver: bridge

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:7'
    networks:
      - app-tier
    ports:
      - '9200:9200'
    environment:
      - ELASTICSEARCH_USERNAME=root
      - ELASTICSEARCH_PASSWORD=root123
    volumes:
      - D:\docker\elasticsearch:/bitnami/elasticsearch/data