apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  enabled_tracing: "false"
  rest-api-server-port: "8080"
  config-server-url: "http://config-server:8080"
  mysql-url: "jdbc:mysql://mysql-svc:3306/db_zenblog"
  # grpc
  grpc-server-port: "8085"
  grpc-client-post-url: "static://service-post:8085"
  grpc-client-comment-url: "static://service-comment:8085"
  # redis
  redis-host: "redis-svc"
  redis-port: "6379"
  # service uaa
  service-uaa-url: "http://service-uaa:8080"
  service-post-url: "http://service-post:8080"
  service-comment-url: "http://service-comment:8080"