server:
  port: ${HTTP_SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      routes:
        - id: uaa
          uri: ${SERVICE_UAA_URL:http://localhost:9001/}
          predicates:
            - Path=/api/uaa/**
          filters:
            - StripPrefix=2
        - id: post
          uri: ${SERVICE_POST_URL:http://localhost:9002/}
          predicates:
            - Path=/api/post/**
          filters:
            - StripPrefix=2
        - id: comment
          uri: ${SERVICE_COMMENT_URL:http://localhost:9003/}
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=2
        - id: rtm-ws
          uri: ${SERVICE_RTM_WS_URL:ws://localhost:9004/}
          predicates:
            - Path=/ws/rtm/**
          filters:
            - StripPrefix=2
        - id: chat
          uri: ${SERVICE_CHAT_URL:http://localhost:9005/}
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=2
        - id: faker
          uri: ${SERVICE_FAKER_URL:http://localhost:9900/}
          predicates:
            - Path=/api/faker/**
          filters:
            - StripPrefix=2
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root123}
      port: ${REDIS_PORT:6379}

api:
  non-auth: /api/test1, /api/test2

jwt:
  issuer: ${JWT_ISSUER:ec.sys}
  algorithm-name: ${JWT_ALGORITHM_NAME:HS512}
  access-token-expire-in-second: ${ACCESS_TOKEN_EXPIRE_IN_SECOND:864000}
  refresh-token-expire-in-second: ${REFRESH_TOKEN_EXPIRE_IN_SECOND:1728000}
  secret: ${JWT_SECRET:123@abc}

#management
management:
  #spring actuator
  endpoints:
    web:
      exposure:
        include:
          - health
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: never
  #tracing
  tracing:
    enabled: ${ENABLED_TRACING:false}
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    # traceID and spanId are predefined MDC keys - we want the logs to include them
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"