spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#management
management:
  #tracing
  tracing:
    enabled: false
  #spring actuator
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    enabled: false
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}