server:
  port: ${HTTP_SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      routes:
        - id: uaa
          uri: ${SERVICE_UAA_URL:http://localhost:9001/}
          predicates:
            - Path=/api/uaa/**
          filters:
            - StripPrefix=2
        - id: post
          uri: ${SERVICE_POST_URL:http://localhost:9002/}
          predicates:
            - Path=/api/post/**
          filters:
            - StripPrefix=2
        - id: comment
          uri: ${SERVICE_COMMENT_URL:http://localhost:9003/}
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=2
        - id: rtm-ws
          uri: ${SERVICE_RTM_WS_URL:ws://localhost:9004/}
          predicates:
            - Path=/ws/rtm/**
          filters:
            - StripPrefix=2
        - id: rtm-api
          uri: ${SERVICE_RTM_URL:http://localhost:9004/}
          predicates:
            - Path=/api/rtm/**
          filters:
            - StripPrefix=2
        - id: chat
          uri: ${SERVICE_CHAT_URL:http://localhost:9005/}
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=2
        - id: faker
          uri: ${SERVICE_FAKER_URL:http://localhost:9900/}
          predicates:
            - Path=/api/faker/**
          filters:
            - StripPrefix=2
        - id: order
          uri: ${SERVICE_UAA_URL:http://localhost:9100/}
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: graphiql
          uri: ${SERVICE_GRAPH_QL_URL:http://localhost:3001/}
          predicates:
            - Path=/graphql/employee/**
          filters:
            - StripPrefix=2
        - id: product
          uri: ${SERVICE_PRODUCT_URL:http://localhost:9103/}
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2
        - id: product-search
          uri: ${SERVICE_PRODUCT_SEARCH_URL:lb://service-product-search}
          predicates:
            - Path=/api/product-search/**
          filters:
            - StripPrefix=2
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root123}
      port: ${REDIS_PORT:6379}

api:
  non-auth: /api/test1, /api/test2

jwt:
  issuer: ${JWT_ISSUER:ec.sys}
  algorithm-name: ${JWT_ALGORITHM_NAME:HS512}
  access-token-expire-in-second: ${ACCESS_TOKEN_EXPIRE_IN_SECOND:864000}
  refresh-token-expire-in-second: ${REFRESH_TOKEN_EXPIRE_IN_SECOND:1728000}
  secret: ${JWT_SECRET:123@abc}

eureka:
  client:
    enabled: false