server:
  port: ${HTTP_SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: uaa
          uri: ${SERVICE_UAA_URL:http://localhost:9001/}
          predicates:
            - Path=/api/uaa/**
          filters:
            - StripPrefix=2
        - id: post
          uri: lb://service-post
          predicates:
            - Path=/api/post/**
          filters:
            - StripPrefix=2
        - id: comment
          uri: lb://service-comment
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=2
  data:
    mongodb:
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root123}
      port: ${REDIS_PORT:6379}
  zipkin:
    enabled: ${ENABLED_ZIPKIN:false}

api:
  non-auth: /api/test1, /api/test2

jwt:
  issuer: ${JWT_ISSUER:ec.sys}
  algorithm-name: ${JWT_ALGORITH_NAME:HS512}
  access-token-expire-in-second: ${ACCESS_TOKEN_EXPIRE_IN_SECOND:864000}
  refresh-token-expire-in-second: ${REFRESH_TOKEN_EXPIRE_IN_SECOND:1728000}
  secret: ${JWT_SECRET:123@abc}

#management
management:
  #spring actuator
  endpoints:
    web:
      exposure:
        include:
          - health
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: never
  #tracing
  tracing:
    enabled: 'false'
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"