spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#management
management:
  #tracing
  tracing:
    enabled: false
  #spring actuator
  endpoints:
    web:
      exposure:
        include: "*"