version: '2'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: 'bitnami/mysql:8.0'
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=db_zenblog
    networks:
      - app-tier
    ports:
      - 3306:3306
  redis:
    image: 'bitnami/redis:6.2'
    environment:
      - REDIS_PASSWORD=root123
    networks:
      - app-tier
    ports:
      - 6379:6379
  zipkin:
    image: 'openzipkin/zipkin:2'
    networks:
      - app-tier
    ports:
      - 9411:9411
  #  rabbitmq
  rabbitmq:
    image: 'longdd90jp/rabbitmq:1.0'
    networks:
      - app-tier
    ports:
      - '5672:5672'
      - '5673:5673'
#  app:
#    build: ./app
#    ports:
#      - "8080:8080"
#    container_name: app
#  prometheus:
#    image: "prom/prometheus"
#    volumes:
#      - ./data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    container_name: prometheus
#  grafana:
#    image: "grafana/grafana"
#    ports:
#      - "3000:3000"
#    container_name: grafana
#  willfarrell:
#    image: "willfarrell/ping:latest"
#    container_name: willfarrell