version: '2'

networks:
  app-tier:
    driver: bridge

services:
  localstack:
    image: localstack/localstack:3.3
    ports:
      - 4566:4566
    environment:
      - SERVICES=sns,sqs,ses,dynamodb,s3,kinesis
      - DEFAULT_REGION=eu-east-1
      - USE_SINGLE_REGION=true
    volumes:
      - ./tmp/localstack/local-aws-infrastructure.sh:/docker-entrypoint-initaws.d/init.sh
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0-legacy
    ports:
      - 8888:8080
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/stratospheric-realm.json
    volumes:
      - ./tmp/keycloak/stratospheric-realm.json:/tmp/stratospheric-realm.json