
server:
  port: ${REST_SERVER_PORT:9103}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-product-search
  datasource:
    url: ${MYSQL_SLAVE_URL:jdbc:mysql:loadbalance://localhost:3307,localhost:3308/db_product?loadBalanceConnectionGroup=first&ha.enableJMX=true&useSSL=false}
    username: ${MYSQL_SLAVE_USERNAME:tit}
    password: ${MYSQL_SLAVEPASSWORD:dangtit90}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  graphql:
    graphiql:
      enabled: true

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:1503}