
server:
  port: ${REST_SERVER_PORT:9104}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-product-search
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  graphql:
    graphiql:
      enabled: true
  elasticsearch:
    uris: ${ELASTIC_SEARCH_URL:http://localhost:9200}
    username: root
    password: root123
  data:
    elasticsearch:
      repositories:
        enabled: true
db:
  driverClassName: com.mysql.cj.jdbc.Driver
  slave:
    url: ${MYSQL_SLAVE_URL:jdbc:mysql:loadbalance://localhost:3307,localhost:3308/db_product}?allowPublicKeyRetrieval=true&useSSL=false&loadBalanceConnectionGroup=first&ha.enableJMX=true
    username: ${MYSQL_SLAVE_USERNAME:tit}
    password: ${MYSQL_SLAVEPASSWORD:dangtit90}

redis:
  master:
    host: localhost
    port: 6380
    password: root123
  slaves:
    - host: localhost
      port: 6377
    - host: localhost
      port: 6378

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:1504}