
spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-batch
  output:
    ansi:
      enabled: always

mysql:
  clients:
    - name: order
      uri: ${MYSQL_ORDER_URL:mongodb://localhost:27017/db_ec}
    - name: inventory
      uri: ${MYSQL_INVENTORY_URL:mongodb://localhost:27017/db_ec}
    - name: customer
      uri: ${MYSQL_CUSTOMER_URL:mongodb://localhost:27017/db_ec}

mongo:
  clients:
    - name: chat
      uri: ${MONGO_CHAT_URL:mongodb://localhost:27017/zenblog_chat}
    - name: rtm
      uri: ${MONGO_RTM_URL:mongodb://localhost:27017/zenblog_rtm}

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:1500}
  client:
    comment:
      address: ${GRPC_CLIENT_COMMENT_URL:static://localhost:1103}
      negotiationType: plaintext

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    # traceID and spanId are predefined MDC keys - we want the logs to include them
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"