apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-uaa
spec:
  replicas: 2
  selector:
    matchLabels:
      component: service-uaa-pod
  template:
    metadata:
      labels:
        component: service-uaa-pod
    spec:
      containers:
        - name: service-uaa-ctn
          image: longdd90jp/aws-service-uaa
          ports:
            - containerPort: 8080
              name: rest-port
            - containerPort: 8085
              name: grpc-port
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REST_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: rest-api-server-port
            # redis evn
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: redis-password
            # mysql evn
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: mysql-url
            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mysql-password