apiVersion: v1
kind: Service
metadata:
  name: service-uaa
  labels:
    component: service-uaa
spec:
  type: ClusterIP
  selector:
    component: service-uaa-pod
  ports:
    - port: 8080
      targetPort: 8080