spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: batch-order-outbox
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_order}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always

#grpc
grpc:
  client:
    inventory:
      address: ${GRPC_CLIENT_COMMENT_URL:static://localhost:1501}
      negotiationType: plaintext
    customer:
      address: ${GRPC_CLIENT_COMMENT_URL:static://localhost:1502}
      negotiationType: plaintext

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    # traceID and spanId are predefined MDC keys - we want the logs to include them
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
job:
  order-outbox:
    scheduled: ${ORDER-OUTBOX-SCHEDULED:30}