server:
  port: ${REST_SERVER_PORT:9002}
  servlet:
    context-path: /post

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-post
  output:
    ansi:
      enabled: always

  cloud:
    openfeign:
      client:
        config:
          commentClient:
            url: ${SERVICE_COMMENT_URL:http://localhost:9003/comment}
#management
management:
  #spring actuator
  endpoints:
    web:
      exposure:
        include:
          - health
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: never

#logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    # traceID and spanId are predefined MDC keys - we want the logs to include them
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"