apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-pod
  template:
    metadata:
      labels:
        app: api-gateway-pod
    # The imp stuff
    spec:
      # Deployment has 2 containers!
      containers:
        - name: api-gateway-envoy
          image: envoyproxy/envoy:distroless-dev
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/local/bin/envoy"
          args:
            - "-c /etc/envoy/envoy.yaml"
          ports:
            - containerPort: 5199
              name: envoy-port
          volumeMounts:
            - name: configs
              mountPath: /etc/envoy
        - name: api-gateway
          image: longdd90jp/aws-api-gateway
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: env-config
            - configMapRef:
                name: api-gateway-envs
            - secretRef:
                name: env-secret
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: configs
          configMap:
            name: api-gateway-files