apiVersion: v1
kind: Service
metadata:
  name: mainapp-envoy-sidecar-svc
spec:
  type: ClusterIP
  selector:
    app: mainapp-envoy-sidecar
  ports:
    # Service only exposes the Envoy container
    - name: mainapp-envoy-sidecar-svc-port
      protocol: TCP
      port: 5199
      targetPort: envoy-port