apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  enabled_zipkin: "false"
  rest-api-server-port: "8080"
  config-server-url: "http://config-server:8080"
  mysql-url: "jdbc:mysql://mysql-svc:3306/db_zenblog"
  # redis
  redis-host: "redis-svc"
  redis-port: "6379"
  # service uaa
  service-uaa-url: "http://service-uaa:8080"