apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    name: db-pv
spec:
  # storage name use in pvc
  storageClassName: db-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # storage path in cluster
    path: "/data/pv0001/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    name: mysql-pvc
spec:
  storageClassName: db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi