apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-zenblog
  labels:
    name: db-pv-zenblog
spec:
  # storage name use in pvc
  storageClassName: db-pv-zenblog
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # storage path in cluster
    path: "/data/pv0002/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-zenblog
  labels:
    name: mysql-pvc-zenblog
spec:
  storageClassName: db-pv-zenblog
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi