apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    name: mysql-pvc
spec:
  storageClassName: db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
