apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-comment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: service-comment-pod
  template:
    metadata:
      labels:
        component: service-comment-pod
    spec:
      containers:
        - name: service-comment-ctn
          image: longdd90jp/aws-service-comment
          ports:
            - containerPort: 8080
              name: rest-port
            - containerPort: 8085
              name: grpc-port
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REST_SERVER_PORT