apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: aws-service-comment
build:
  artifacts:
    - image: longdd90jp/aws-service-comment
      jib:
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/**.yaml
