server:
  port: ${REST_SERVER_PORT:9003}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-comment
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_zenblog}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:1103}
  client:
    post:
      address: ${GRPC_CLIENT_POST_URL:static://localhost:1102}
      negotiationType: plaintext
    GLOBAL:
      default-load-balancing-policy: