server:
  port: ${HTTP_SERVER_PORT:8061}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/