spring:
  cloud:
    aws:
      credentials:
        profile:
          path: ${AWS_CREDENTAIL_PATH:foo}
      region:
        static: ${AWS_DEFAULT_REGION:us-east-1}

management:
  cloudwatch:
    metrics:
      export:
        enabled: false

custom:
  environment: aws
  aws:
    sns:
      topic-order-process-arn: arn:aws:sns:us-east-1:533267003640:order-process-topic

logging:
  level:
    io:
      awspring:
        cloud: error