server:
  port: ${REST_SERVER_PORT:9003}

spring:
  application:
    name: service-comment
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_zenblog
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none