server:
  port: ${REST_SERVER_PORT:9001}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-uaa
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_zenblog}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root123}
      port: ${REDIS_PORT:6379}

jwt:
  issuer: ${JWT_ISSUER:ec.sys}
  algorithm-name: ${JWT_ALGORITHM_NAME:HS512}
  access-token-expire-in-second: ${ACCESS_TOKEN_EXPIRE_IN_SECOND:864000}
  refresh-token-expire-in-second: ${REFRESH_TOKEN_EXPIRE_IN_SECOND:1728000}
  secret: ${JWT_SECRET:123@abc}

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9011}