apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-comment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: service-comment-pod
  template:
    metadata:
      labels:
        component: service-comment-pod
    spec:
      containers:
        - name: service-comment-ctn
          image: longdd90jp/aws-service-comment
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: rest-port
            - containerPort: 8085
              name: grpc-port
          envFrom:
            - configMapRef:
                name: env-config
            - configMapRef:
                name: service-comment-envs
            - secretRef:
                name: env-secret
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
# envoy proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-envoy-proxy
  labels:
    app: comment-envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-envoy-proxy-pod
  template:
    metadata:
      labels:
        app: comment-envoy-proxy-pod
    # The imp stuff
    spec:
      # Deployment has 1 container!
      containers:
        - name: comment-envoy-proxy-ctn
          image: envoyproxy/envoy:distroless-dev
          imagePullPolicy: IfNotPresent
          command:
            - "/usr/local/bin/envoy"
          args:
            - "-c /etc/envoy/envoy.yaml"
          ports:
            - containerPort: 5199
              name: rest-envoy-port
            - containerPort: 5195
              name: grpc-envoy-port
          volumeMounts:
            - name: configs
              mountPath: /etc/envoy
      volumes:
        - name: configs
          configMap:
            name: service-comment-files