apiVersion: v1
kind: Service
metadata:
  name: local-service-comment
spec:
  type: ClusterIP
  selector:
    component: service-comment-pod
  ports:
    - port: 8080
      protocol: TCP
      name: rest-port
      targetPort: 8080
    - port: 8085
      protocol: TCP
      name: grpc-port
      targetPort: 8085

---
# envoy proxy
apiVersion: v1
kind: Service
metadata:
  name: service-comment
spec:
  type: ClusterIP
  selector:
    app: comment-envoy-proxy-pod
  ports:
    # Service only exposes the Envoy container
    - name: rest-envoy-port
      protocol: TCP
      port: 8080
      targetPort: rest-envoy-port
    - name: grpc-envoy-port
      protocol: TCP
      port: 8085
      targetPort: grpc-envoy-port