apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-post
spec:
  replicas: 3
  selector:
    matchLabels:
      component: service-post-pod
  template:
    metadata:
      labels:
        component: service-post-pod
    spec:
      containers:
        - name: service-post-ctn
          image: longdd90jp/aws-service-post
          ports:
          - containerPort: 8080
            name: rest-port
          - containerPort: 8085
            name: grpc-port
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Health-Check-Header
                  value: system
            initialDelaySeconds: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
                - name: Ready-Check-Header
                  value: system
            initialDelaySeconds: 5
            timeoutSeconds: 2