apiVersion: v1
kind: Service
metadata:
  name: service-post
  labels:
    component: service-post
spec:
  type: ClusterIP
  selector:
    component: service-post-pod
  ports:
    - port: 8080
      targetPort: 8080