
server:
  port: ${REST_SERVER_PORT:9103}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: service-product
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
db:
  driverClassName: com.mysql.cj.jdbc.Driver
  master:
    url: ${MYSQL_MASTER_URL:jdbc:mysql://localhost:3309/db_product}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_MASTER_USERNAME:tit}
    password: ${MYSQL_MASTER_PASSWORD:dangtit90}
  slave:
    url: ${MYSQL_SLAVE_URL:jdbc:mysql:loadbalance://localhost:3307,localhost:3308/db_product}?allowPublicKeyRetrieval=true&useSSL=false&loadBalanceConnectionGroup=first&ha.enableJMX=true
    username: ${MYSQL_SLAVE_USERNAME:tit}
    password: ${MYSQL_SLAVEPASSWORD:dangtit90}

#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:1503}