spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
db:
  driverClassName: com.mysql.cj.jdbc.Driver
  master:
    url: ${MYSQL_MASTER_URL:jdbc:mysql://localhost:3309/db_product}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_MASTER_USERNAME:tit}
    password: ${MYSQL_MASTER_PASSWORD:dangtit90}
  slave:
    url: ${MYSQL_SLAVE_URL:jdbc:mysql:loadbalance://localhost:3307,localhost:3308/db_product?loadBalanceConnectionGroup=first&ha.enableJMX=true&useSSL=false}
    username: ${MYSQL_SLAVE_USERNAME:tit}
    password: ${MYSQL_SLAVEPASSWORD:dangtit90}