apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: dev-infa
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prometheus-server-pod
  template:
    metadata:
      labels:
        component: prometheus-server-pod
    spec:
      containers:
        - name: prometheus-server-ctn
          image: prom/prometheus:v2.52.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
              name: ctn-port
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf

        - name: prometheus-storage-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: dev-infa
  labels:
    component: prometheus-server
spec:
  type: ClusterIP
  selector:
    component: prometheus-server-pod
  ports:
    - port: 9090
      protocol: TCP
      targetPort: ctn-port