apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: aws-api-gateway
build:
  artifacts:
    - image: longdd90jp/aws-api-gateway
      docker:
        cacheFrom:
          - longdd90jp/aws-api-gateway
  local: {}
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/**.yaml
