apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo
  labels:
    name: mongo-pv
spec:
  # storage name use in pvc
  storageClassName: mongo-pv
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # storage path in cluster
    path: "/data/pv0010/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mongo
  labels:
    name: mongo-pvc
spec:
  storageClassName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi