apiVersion: v1
kind: Service
metadata:
  name: service-uaa
spec:
  type: ClusterIP
  selector:
    app: service-uaa-pod
  ports:
    # Service only exposes the Envoy container
    - name: envoy-port
      protocol: TCP
      port: 8080
      targetPort: envoy-port