server:
  port: ${REST_SERVER_PORT:9000}

spring:
  application:
    name: config-server
  # profile
  profiles:
    active: native
  # security
  security:
    user:
      name: ${CONFIG_ACCESS_USERNAME:root}
      password: ${CONFIG_ACCESS_PASSWORD:s3cr3t}
management:
  endpoints:
    web:
      exposure:
        include:
          - health
    enabled-by-default: 'false'
  endpoint:
    health:
      enabled: 'true'
      show-details: never