---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: api-gateway-files
    files:
      - configs/envoy.yaml
  - name: api-gateway-envs
    env: configs/envs.properties
